@startuml oidc

Cliente -> "Servidor de Autorización": \
  1. Redirección \n - Scope: "openid"

"Servidor de Autorización" -> "Servidor de Autorización": \
  2. Autenticación \n - Nombre de Usuario \n - Contraseña \n - etc.

"Servidor de Autorización" -> Cliente: \
  3. Redirección \n - Código de Autorización

Cliente -> "Servidor de Autorización": \
  4. Intercambio del Código de Autorización \n - Código de Autorización

"Servidor de Autorización" -> Cliente: \
  5. Respuesta del Intercambio \n - Token de Identidad \n - Token de Acceso \
  \t\t\t\t\t\t\t\t\t\t

@enduml
